// next/components/DiywbEditor.tsx
"use client";

import { useEffect, useRef } from "react";
import DIYWebsiteBuilderEditor from "@diy-website-builder/sdk";

type DiywbEditorProps = {
  apiKey: string;
  shortId: string;
  exitURL?: string;
  onPublish?: (url?: string) => void;
};

/**
 * Client-only mount for the SDK. Always destroy on unmount so Next route
 * changes do not leave orphan editor UI in the DOM.
 */
export function DiywbEditor({
  apiKey,
  shortId,
  exitURL,
  onPublish,
}: DiywbEditorProps) {
  const containerRef = useRef<HTMLDivElement>(null);
  const onPublishRef = useRef(onPublish);
  onPublishRef.current = onPublish;

  useEffect(() => {
    const container = containerRef.current;
    if (!container) return;

    const editor = new DIYWebsiteBuilderEditor.Builder({
      apiKey,
      shortId,
      container,
      exitURL,
      onPublish: (url) => onPublishRef.current?.(url),
    });

    return () => {
      editor.destroy();
    };
  }, [apiKey, shortId, exitURL]);

  return <div ref={containerRef} className="editor-mount" />;
}

// vue/src/DiywbEditor.vue
<script setup lang="ts">
import { onBeforeUnmount, onMounted, ref, watch } from "vue";
import DIYWebsiteBuilderEditor from "@diy-website-builder/sdk";

const props = defineProps<{
  apiKey: string;
  shortId: string;
  exitUrl?: string;
}>();

const emit = defineEmits<{
  publish: [url?: string];
}>();

const containerRef = ref<HTMLDivElement | null>(null);
let editor: { destroy: () => void } | undefined;

function mountEditor() {
  editor?.destroy();
  editor = undefined;
  const container = containerRef.value;
  if (!container) return;

  editor = new DIYWebsiteBuilderEditor.Builder({
    apiKey: props.apiKey,
    shortId: props.shortId,
    container,
    exitURL: props.exitUrl,
    onPublish: (url) => emit("publish", url),
  });
}

onMounted(mountEditor);
watch(
  () => [props.apiKey, props.shortId, props.exitUrl] as const,
  () => mountEditor(),
);
onBeforeUnmount(() => {
  editor?.destroy();
  editor = undefined;
});
</script>

<template>
  <div ref="containerRef" class="editor-mount" />
</template>
